name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends make gcc libc6-dev

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install mingw make -y

      - name: Build Native Library
        run: make

      - name: Strip Native Library (Linux)
        if: runner.os == 'Linux'
        run: strip libturbo.so
      
      - name: Strip Native Library (Windows)
        if: runner.os == 'Windows'
        run: strip turbo.dll

      - name: Determine release body
        run: |
          echo "$(git log --oneline --no-decorate $(git describe --tags --abbrev=0 @^)..@)" > release_body.txt

      - name: Release
        uses: softprops/action-gh-release@master
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "release draft"
          draft: true
          files: |
            turbo.dll
            libturbo.so
            libturbo.dylib
          body_path: release_body.txt
